apiVersion: v1
kind: Namespace
metadata:
  name: edison
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edison
  namespace: edison
spec:
  replicas: 1
  selector:
    matchLabels: { app.kubernetes.io/name: edison }
  template:
    metadata:
      labels: { app.kubernetes.io/name: edison }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
      containers:
        - name: edison
          image: edison:0.1.0
          ports: [{ containerPort: 8080 }]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 500m, memory: 256Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: edison
  namespace: edison
spec:
  selector: { app.kubernetes.io/name: edison }
  ports: [{ port: 8080, targetPort: 8080 }]
---
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: edison
  namespace: edison
spec:
  network:
    expose:
      - service: edison
        selector: { app.kubernetes.io/name: edison }
        gateway: tenant
        host: edison
        port: 8080
  sso:
    - name: Edison
      clientId: uds-edison
      redirectUris:
        - "https://edison.uds.dev/login"
      enableAuthserviceSelector:
        app.kubernetes.io/name: edison
